package studio

import (
	"archive/zip"
	"encoding/csv"
	"encoding/json"
	"fmt"
	"net/http"
	"strings"
	"time"

	"github.com/gin-gonic/gin"
)

// ExportAllData handles GET /api/export/data?format=json|csv|sql
func (h *Handlers) ExportAllData(c *gin.Context) {
	format := c.DefaultQuery("format", "json")

	switch format {
	case "json":
		h.exportAllDataJSON(c)
	case "csv":
		h.exportAllDataCSV(c)
	case "sql":
		h.exportAllDataSQL(c)
	default:
		c.JSON(http.StatusBadRequest, gin.H{"error": "unsupported format: " + format + ". Use json, csv, or sql"})
	}
}

// exportBatchSize is how many rows are read from the DB at a time when
// streaming a full-database export, so a multi-million-row table doesn't have
// to be held in memory all at once.
const exportBatchSize = 1000

// streamRows reads a table in Scope-constrained pages of exportBatchSize and
// invokes fn for each row, so an export never holds a whole table in memory.
// Rows are ordered by primary key (when known) so paging is stable.
func (h *Handlers) streamRows(c *gin.Context, table string, fn func(row map[string]interface{})) {
	pk := ""
	if ti := h.getTableInfo(table); ti != nil {
		pk = getPrimaryKey(h.Schema, table)
	}
	offset := 0
	for {
		var batch []map[string]interface{}
		q := h.scoped(c, table)
		if pk != "" {
			q = q.Order(h.qi(pk))
		}
		if err := q.Offset(offset).Limit(exportBatchSize).Find(&batch).Error; err != nil {
			return
		}
		for i := range batch {
			fn(batch[i])
		}
		if len(batch) < exportBatchSize {
			return
		}
		offset += len(batch)
	}
}

// csvCell renders a value as a CSV field, neutralizing spreadsheet formula
// injection by prefixing a leading =, +, -, or @ with a single quote.
func csvCell(val interface{}) string {
	if val == nil {
		return ""
	}
	s := fmt.Sprintf("%v", val)
	if len(s) > 0 && (s[0] == '=' || s[0] == '+' || s[0] == '-' || s[0] == '@') {
		s = "'" + s
	}
	return s
}

func jsonValue(v interface{}) string {
	b, err := json.Marshal(v)
	if err != nil {
		return "null"
	}
	return string(b)
}

func (h *Handlers) exportAllDataJSON(c *gin.Context) {
	c.Header("Content-Disposition", "attachment; filename=database_export.json")
	c.Header("Content-Type", "application/json")
	w := c.Writer

	fmt.Fprintf(w, `{"database":%s,"driver":%s,"exported_at":%s,"tables":{`,
		jsonValue(h.Schema.Database), jsonValue(h.Schema.Driver),
		jsonValue(time.Now().UTC().Format(time.RFC3339)))

	firstTable := true
	for _, table := range h.visibleSchema().Tables {
		colNames := make([]string, len(table.Columns))
		for i, col := range table.Columns {
			colNames[i] = col.Name
		}

		if !firstTable {
			_, _ = w.WriteString(",")
		}
		firstTable = false
		fmt.Fprintf(w, `%s:{"columns":%s,"rows":[`, jsonValue(table.Name), jsonValue(colNames))

		var rowCount int64
		firstRow := true
		h.streamRows(c, table.Name, func(row map[string]interface{}) {
			if !firstRow {
				_, _ = w.WriteString(",")
			}
			firstRow = false
			_, _ = w.WriteString(jsonValue(row))
			rowCount++
		})

		fmt.Fprintf(w, `],"row_count":%d}`, rowCount)
	}

	_, _ = w.WriteString("}}")
}

func (h *Handlers) exportAllDataCSV(c *gin.Context) {
	c.Header("Content-Type", "application/zip")
	c.Header("Content-Disposition", "attachment; filename=database_export.zip")

	zw := zip.NewWriter(c.Writer)
	defer zw.Close()

	for _, table := range h.visibleSchema().Tables {
		w, err := zw.Create(table.Name + ".csv")
		if err != nil {
			continue
		}
		csvWriter := csv.NewWriter(w)

		// Header
		colNames := make([]string, len(table.Columns))
		for i, col := range table.Columns {
			colNames[i] = col.Name
		}
		_ = csvWriter.Write(colNames)

		// Data rows, streamed in batches
		cols := table.Columns
		h.streamRows(c, table.Name, func(row map[string]interface{}) {
			record := make([]string, len(cols))
			for i, col := range cols {
				record[i] = csvCell(row[col.Name])
			}
			_ = csvWriter.Write(record)
		})
		csvWriter.Flush()
	}
}

func (h *Handlers) exportAllDataSQL(c *gin.Context) {
	c.Header("Content-Disposition", "attachment; filename=database_export.sql")
	c.Header("Content-Type", "text/sql; charset=utf-8")
	w := c.Writer

	fmt.Fprintf(w, "-- Database export generated by GORM Studio\n")
	fmt.Fprintf(w, "-- Driver: %s\n", h.Schema.Driver)
	fmt.Fprintf(w, "-- Exported at: %s\n\n", time.Now().UTC().Format(time.RFC3339))

	driver := h.DB.Dialector.Name()

	for _, table := range h.visibleSchema().Tables {
		cols := table.Columns
		wroteHeader := false
		h.streamRows(c, table.Name, func(row map[string]interface{}) {
			colNames := make([]string, 0, len(cols))
			values := make([]string, 0, len(cols))
			for _, col := range cols {
				val := row[col.Name]
				if val == nil {
					continue
				}
				colNames = append(colNames, quoteIdent(driver, col.Name))
				values = append(values, formatSQLValue(val))
			}
			if len(colNames) == 0 {
				return
			}
			if !wroteHeader {
				fmt.Fprintf(w, "-- Table: %s\n", table.Name)
				wroteHeader = true
			}
			fmt.Fprintf(w, "INSERT INTO %s (%s) VALUES (%s);\n",
				quoteIdent(driver, table.Name),
				strings.Join(colNames, ", "),
				strings.Join(values, ", "))
		})
		if wroteHeader {
			_, _ = w.WriteString("\n")
		}
	}
}

// formatSQLValue formats a Go value as a SQL literal.
func formatSQLValue(val interface{}) string {
	if val == nil {
		return "NULL"
	}
	switch v := val.(type) {
	case float64:
		if v == float64(int64(v)) {
			return fmt.Sprintf("%d", int64(v))
		}
		return fmt.Sprintf("%g", v)
	case bool:
		if v {
			return "1"
		}
		return "0"
	case string:
		escaped := strings.ReplaceAll(v, "'", "''")
		return "'" + escaped + "'"
	default:
		escaped := strings.ReplaceAll(fmt.Sprintf("%v", v), "'", "''")
		return "'" + escaped + "'"
	}
}
